In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[ 1.05472041  0.78159369  1.17120158 -0.09731781 -0.94686013]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 1.05472041  0.78159369  1.17120158 -0.09731781 -0.94686013]


In [6]:
print(np.dot(a, a.T))

4.001051847130049


In [7]:
a = np.random.randn(5, 1)
print(a)

[[ 0.45691275]
 [-0.87407205]
 [-1.06663772]
 [ 0.07457623]
 [-1.19123578]]


In [8]:
print(a.T)

[[ 0.45691275 -0.87407205 -1.06663772  0.07457623 -1.19123578]]


In [9]:
print(np.dot(a, a.T))

[[ 0.20876926 -0.39937467 -0.48736038  0.03407483 -0.54429082]
 [-0.39937467  0.76400195  0.93231822 -0.065185    1.0412259 ]
 [-0.48736038  0.93231822  1.13771602 -0.07954582  1.27061701]
 [ 0.03407483 -0.065185   -0.07954582  0.00556161 -0.08883787]
 [-0.54429082  1.0412259   1.27061701 -0.08883787  1.41904268]]
